repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        name: mypy
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: flake8
        args: [--max-line-length=120, --exclude=ndtp/tests/test_main.py]
#        args: ["--ignore=E302"]
